"""add sonny memories

Revision ID: dbfd632bc985
Revises: 57e2c4eee326
Create Date: 2026-07-04 15:01:52.762305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbfd632bc985'
down_revision: Union[str, Sequence[str], None] = '57e2c4eee326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sonny_memories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('memory_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sonny_memories_company_id'), 'sonny_memories', ['company_id'], unique=False)
    op.create_index(op.f('ix_sonny_memories_memory_type'), 'sonny_memories', ['memory_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sonny_memories_memory_type'), table_name='sonny_memories')
    op.drop_index(op.f('ix_sonny_memories_company_id'), table_name='sonny_memories')
    op.drop_table('sonny_memories')
    # ### end Alembic commands ###
