import type { OSCommand } from "./types";

export const sharedCommands: OSCommand[] = [];

export const tenantCommands: OSCommand[] = [
  {
    id: "tenant-command-center",
    title: "Command Center",
    subtitle: "Open the tenant executive dashboard.",
    category: "Pages",
    keywords: ["dashboard", "home", "workspace", "executive"],
    route: "/dashboard",
  },
  {
    id: "tenant-companies",
    title: "Switch Company",
    subtitle: "Select another tenant workspace.",
    category: "Company",
    keywords: ["company", "tenant", "workspace", "switch"],
    route: "/companies",
  },
  {
    id: "tenant-create-company",
    title: "Create Company",
    subtitle: "Launch a new company workspace.",
    category: "Actions",
    keywords: ["new", "company", "business", "create"],
    route: "/create-company",
  },
  {
    id: "tenant-sonny",
    title: "Open Sonny AI COO",
    subtitle: "Coordinate the company through Sonny.",
    category: "AI",
    keywords: ["sonny", "ai", "coo", "assistant"],
    route: "/sonny",
  },
  {
    id: "tenant-hermes",
    title: "Open Hermes Compliance",
    subtitle: "Review documents and compliance.",
    category: "AI",
    keywords: ["hermes", "compliance", "documents", "legal"],
    route: "/hermes",
  },
  {
    id: "tenant-ai-workforce",
    title: "AI Workforce",
    subtitle: "Manage the tenant AI workforce.",
    category: "AI",
    keywords: ["agents", "workers", "ai", "team"],
    route: "/ai-workforce",
  },
  {
    id: "tenant-documents",
    title: "Document Vault",
    subtitle: "Search and manage company documents.",
    category: "Actions",
    keywords: ["files", "documents", "vault", "compliance"],
    route: "/documents",
  },
  {
    id: "tenant-tasks",
    title: "Tasks",
    subtitle: "Open company tasks.",
    category: "Actions",
    keywords: ["task", "work", "todo", "assignment"],
    route: "/tasks",
  },
  {
    id: "tenant-billing",
    title: "Billing Center",
    subtitle: "Open tenant billing and invoices.",
    category: "Company",
    keywords: ["billing", "invoice", "payment", "ledger"],
    route: "/billing",
  },
  {
    id: "tenant-notifications",
    title: "Notifications",
    subtitle: "Open the notification archive.",
    category: "Company",
    keywords: ["alerts", "updates", "notification"],
    route: "/notifications",
  },
  {
    id: "tenant-settings",
    title: "Settings",
    subtitle: "Configure the current workspace.",
    category: "Settings",
    keywords: ["settings", "preferences", "configuration"],
    route: "/settings",
  },
];

export const adminCommands: OSCommand[] = [
  {
    id: "admin-command-center",
    title: "Admin Command Center",
    subtitle: "Open Firmic platform operations.",
    category: "Settings",
    keywords: ["admin", "dashboard", "platform", "overview"],
    route: "/admin",
  },
  {
    id: "admin-companies",
    title: "All Companies",
    subtitle: "Search and manage tenant companies.",
    category: "Settings",
    keywords: ["companies", "tenants", "businesses", "workspaces"],
    route: "/admin-companies",
  },
  {
    id: "admin-offices",
    title: "Office Inventory",
    subtitle: "Manage Firmic office inventory.",
    category: "Actions",
    keywords: ["office", "inventory", "locations", "workspace"],
    route: "/admin-offices",
  },
  {
    id: "admin-compliance",
    title: "Compliance Queue",
    subtitle: "Review platform compliance cases.",
    category: "Actions",
    keywords: ["compliance", "review", "documents", "queue"],
    route: "/admin-compliance",
  },
  {
    id: "admin-billing",
    title: "Tenant Billing",
    subtitle: "Review billing across all tenants.",
    category: "Actions",
    keywords: ["billing", "invoice", "payments", "tenants"],
    route: "/admin-billing",
  },
  {
    id: "admin-support",
    title: "Support Inbox",
    subtitle: "Review tenant support requests.",
    category: "Actions",
    keywords: ["support", "tickets", "inbox", "help"],
    route: "/admin-support",
  },
  {
    id: "admin-ai-workforce",
    title: "AI Workforce Admin",
    subtitle: "Monitor the platform AI workforce.",
    category: "AI",
    keywords: ["ai", "agents", "workforce", "monitoring"],
    route: "/admin-ai-workforce",
  },
  {
    id: "admin-reports",
    title: "Admin Reports",
    subtitle: "Open platform analytics and reports.",
    category: "AI",
    keywords: ["reports", "analytics", "metrics", "intelligence"],
    route: "/admin-analytics",
  },
  {
    id: "admin-users",
    title: "Admin Users & Roles",
    subtitle: "Manage internal users and permissions.",
    category: "Settings",
    keywords: ["users", "roles", "permissions", "employees"],
    route: "/admin-users",
  },
  {
    id: "admin-settings",
    title: "Admin Settings",
    subtitle: "Configure the Firmic platform.",
    category: "Settings",
    keywords: ["settings", "platform", "configuration", "system"],
    route: "/admin-settings",
  },
];
